language: node_js
node_js:
  - "stable"
  - "7.6.0"
install:
  - npm install
  - npm install -g gulp
  - npm install gulp-eslint
  - npm install gulp-mocha
  - npm install chai
script:
  - gulp --gulpfile node_modules/fepper/tasker.js test
